Repository NOW-SOPT-APP8-JUMPIT/Jumpit-iOS, pull requests merged in 2024-05, with the labels that each got.

#13 🍎 [Style] 검색뷰 UI 작업했다 지훈아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/CategoryModel.swift
  Jumpit/CustomNavigationBarView.swift
  Jumpit/JobOptionCollectionViewCell.swift
  Jumpit/LeftAlignedCollectionViewFlowLayout.swift
  Jumpit/ModalPresentationController.swift
  Jumpit/RecentSearchModel.swift
  Jumpit/RecentSearchTableViewCell.swift
  Jumpit/RecentSearchView.swift
  Jumpit/RecentSearchViewController.swift
  Jumpit/SceneDelegate.swift
  Jumpit/SearchResultCollectionView.swift
  Jumpit/SearchResultCollectionViewCell.swift
  Jumpit/SearchResultHeaderView.swift
  Jumpit/SearchResultModel.swift
  Jumpit/SearchResultViewController.swift
  Jumpit/SearchResultViewItem.swift
  Jumpit/SelectedJobOptionsModel.swift
  Jumpit/SortCategoryCollectionViewCell.swift
  Jumpit/SortCategoryView.swift
  Jumpit/SortCategoryViewController.swift
Labels: 👼 민지, 🍎 Style

#15 🧃 [Feat] 폰트 익스텐션 구현했다 지훈아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/UIFont+.swift
  Jumpit/ViewController.swift
Labels: 😎 유진, 🧃Feat

#23 🧃 [Feat] 네트워크 파일 구현했다 지훈아
  .gitignore
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/Network/API/PositionsAPI.swift
  Jumpit/Network/API/ResumesAPI.swift
  Jumpit/Network/Foundation/JumpitBaseAPI.swift
  Jumpit/Network/Foundation/NetworkError.swift
  Jumpit/Network/Foundation/NetworkProvider.swift
  Jumpit/Network/Foundation/PrivacyInfoManager.swift
  Jumpit/Network/Manager/SearchManager.swift
  Jumpit/Network/Response/ResumesResponseDTO.swift
  Jumpit/Network/Response/SearchResultResponseDTO.swift
  Jumpit/Resource/Info.plist
  Jumpit/Source/Core/CustomArrayEncoding.swift
  Jumpit/Source/Home/HomeViewController.swift
Labels: 👼 민지, 👴 지훈, 🧃Feat

#24 🧃 [Feat] SearchView API 연결했다 지훈아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/Source/SearchResult/Model/SearchResultModel.swift
  Jumpit/Source/SearchResult/View/EmptyResultView.swift
  Jumpit/Source/SearchResult/View/SearchResultCollectionView.swift
  Jumpit/Source/SearchResult/View/SearchResultCollectionViewCell.swift
  Jumpit/Source/SearchResult/ViewController/SearchResultViewController.swift
  Jumpit/Source/SortCategory/Model/SelectedJobOptionsModel.swift
  Jumpit/Source/SortCategory/ViewController/SortCategoryViewController.swift
Labels: 👼 민지, 🧃Feat

#25 Feature/fix detail UI err
  Jumpit/Source/Detail/Cell/CompanyInfoCVC.swift
  Jumpit/Source/Detail/Cell/ExpandableCVC.swift
  Jumpit/Source/Detail/Cell/JDCVC.swift
  Jumpit/Source/Detail/Cell/PositionBodyCollectionViewCell.swift
  Jumpit/Source/Detail/Cell/PositionHeaderCollectionViewCell.swift
  Jumpit/Source/Detail/Cell/differenceCVC.swift
  Jumpit/Source/Detail/Cell/rewardCVC.swift
  Jumpit/Source/Detail/DetailViewController.swift
  Jumpit/Source/Detail/View/BottomRegisterVC.swift
  Jumpit/Source/Detail/View/DetailVC.swift
  Jumpit/Source/Detail/model/DetailModel.swift
Labels: 👴 지훈, 🍎 Style, 👼 Minji, 🔧 Fix

#26 🍎 [Style] 이력서 UI 구현했다 지훈아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/Resource/Assets.xcassets/icon/ellipse/icn_ellipse_gray.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/icon/ellipse/icn_ellipse_gray.imageset/icn_ellipse_gray.png
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_help_select 1.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_help_select 1.imageset/icn_help_select.png
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_option.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_option.imageset/icn_option.png
  Jumpit/Resource/Assets.xcassets/img/img_no_file.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/img/img_no_file.imageset/img_no_file.png
  Jumpit/Resource/Assets.xcassets/img/img_no_resume.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/img/img_no_resume.imageset/img_no_resume.png
  Jumpit/Resource/Assets.xcassets/img/img_popup_file.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/img/img_popup_file.imageset/img_popup_file.png
  Jumpit/Resource/Assets.xcassets/img/img_popup_resume.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/img/img_popup_resume.imageset/img_popup_resume.png
  Jumpit/Resource/Extension/UIView+.swift
  Jumpit/Source/Resume/ResumeViewController.swift
  Jumpit/Source/Resume/View/ResumeCollectionViewCell.swift
  Jumpit/Source/Resume/ViewController/ResumeAddViewController.swift
  Jumpit/Source/Resume/ViewController/ResumeEditViewController.swift
  Jumpit/Source/Resume/ViewController/ResumeViewController.swift
Labels: 😎 유진, 🍎 Style

#35 ♻️ [Refactor] 홈 뷰 버튼 세부 조정했다 지훈아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_search_green.imageset/Contents.json
  Jumpit/Resource/Assets.xcassets/icon/etc/icn_search_green.imageset/icn_search_green.svg
  Jumpit/Resource/Extension/UIImage+.swift
  Jumpit/Source/Home/View/HomeSearchButton.swift
Labels: 😎 유진, ♻️ Refactor

#37 🔧[Fix] SearchResultVC에서 DetailVC로 id 전달했다 지훈아
  .gitignore
  Jumpit/Network/Foundation/PrivacyInfo.plist
  Jumpit/Source/Detail/View/DetailVC.swift
  Jumpit/Source/SearchResult/Model/SearchResultModel.swift
  Jumpit/Source/SearchResult/View/SearchResultCollectionView.swift
  Jumpit/Source/SearchResult/View/SearchResultCollectionViewCell.swift
  Jumpit/Source/SearchResult/ViewController/SearchResultViewController.swift
Labels: 👼 민지, 🔧 Fix

#38 PlacrHolder 넣어서 싱크 맞췃다 유진아
  Jumpit.xcodeproj/project.pbxproj
  Jumpit/Resource/PrivacyInfo.plist
  Jumpit/SceneDelegate.swift
  Jumpit/Source/Detail/Cell/ExpandableCVC.swift
  Jumpit/Source/Detail/Cell/PlaceholderCell.swift
  Jumpit/Source/Detail/View/DetailVC.swift
Labels: 👴 지훈, 🧃Feat, 🍎 Style, ♻️ Refactor
